# Generated by Django 3.2.3 on 2021-06-06 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('statistic', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='statistic',
            table='statistic',
        ),
    ]
