# Generated by Django 3.2.3 on 2021-06-06 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statistic', '0002_alter_statistic_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statistic',
            name='clicks',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='statistic',
            name='cost',
            field=models.DecimalField(blank=True, decimal_places=2, default=1, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='statistic',
            name='views',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
