# Generated by Django 3.2.3 on 2021-06-08 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statistic', '0007_alter_statistic_date'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='statistic',
            index=models.Index(fields=['date'], name='statistic_date_c46ea3_idx'),
        ),
    ]
